suite: Controller Secondary Ingress
release:
  name: my-release
  namespace: my-namespace
templates:
  - jenkins-controller-secondary-ingress.yaml
capabilities:
  majorVersion: 1
  minorVersion: 18
tests:
  - it: test defaults
    asserts:
      - hasDocuments:
          count: 0
  - it: enabled
    set:
      "controller.secondaryingress":
        enabled: true
        hostName: jenkins.example.com
        ingressClassName: nginx
        paths:
          - /github-webhook
        tls:
          - secretName: tlsSecret
            hosts:
              - jenkins.example.com
    asserts:
      - isKind:
          of: Ingress
      - equal:
          path: apiVersion
          value: networking.k8s.io/v1beta1
      - equal:
          path: metadata.name
          value: my-release-jenkins-secondary
      - equal:
          path: metadata.namespace
          value: my-namespace
      - matchRegex:
          path: metadata.labels["helm.sh/chart"]
          pattern: ^jenkins-
      - isNull:
          path: metadata.annotations
      - equal:
          path: spec
          value:
            ingressClassName: nginx
            rules:
              - host: jenkins.example.com
                http:
                  paths:
                    - backend:
                        serviceName: my-release-jenkins
                        servicePort: 8080
                      path: /github-webhook
            tls:
              - hosts:
                  - jenkins.example.com
                secretName: tlsSecret
  - it: disable helm.sh label
    set:
      renderHelmLabels: false
      controller.secondaryingress:
        enabled: true
        hostName: jenkins.example.com
        ingressClassName: nginx
        paths:
          - /github-webhook
    asserts:
      - equal:
          path: metadata.labels
          value:
            app.kubernetes.io/component: jenkins-controller
            app.kubernetes.io/instance: my-release
            app.kubernetes.io/managed-by: Helm
            app.kubernetes.io/name: jenkins
  - it: hostName with Release.Name template variable
    set:
      controller.secondaryingress:
        enabled: true
        hostName: jenkins-{{ .Release.Name }}.example.com
        ingressClassName: nginx
        paths:
          - /wsagents/
        tls:
          - secretName: my-tls-secret
            hosts:
              - jenkins-{{ .Release.Name }}.example.com
    asserts:
      - equal:
          path: spec.rules[0].host
          value: jenkins-my-release.example.com
      - equal:
          path: spec.tls[0].hosts[0]
          value: jenkins-my-release.example.com
      - equal:
          path: spec.tls[0].secretName
          value: my-tls-secret
  - it: multiple TLS hosts with Release.Name template variable
    set:
      controller.secondaryingress:
        enabled: true
        hostName: jenkins-{{ .Release.Name }}.example.com
        ingressClassName: nginx
        paths:
          - /wsagents/
        tls:
          - secretName: my-tls-secret
            hosts:
              - jenkins-{{ .Release.Name }}.example.com
              - jenkins-{{ .Release.Name }}.alt.example.com
    asserts:
      - equal:
          path: spec.tls[0].hosts[0]
          value: jenkins-my-release.example.com
      - equal:
          path: spec.tls[0].hosts[1]
          value: jenkins-my-release.alt.example.com
  - it: multiple TLS hosts, some with Release.Name template variable
    set:
      controller.secondaryingress:
        enabled: true
        hostName: jenkins-{{ .Release.Name }}.example.com
        ingressClassName: nginx
        paths:
          - /wsagents/
        tls:
          - secretName: my-tls-secret
            hosts:
              - jenkins-hard-coded.example.com
              - jenkins-{{ .Release.Name }}.alt.example.com
    asserts:
      - equal:
          path: spec.tls[0].hosts[0]
          value: jenkins-hard-coded.example.com
      - equal:
          path: spec.tls[0].hosts[1]
          value: jenkins-my-release.alt.example.com
  - it: TLS without secretName uses default secret
    set:
      controller.secondaryingress:
        enabled: true
        hostName: jenkins.example.com
        ingressClassName: nginx
        paths:
          - /github-webhook
        tls:
          - hosts:
              - jenkins.example.com
    asserts:
      - equal:
          path: spec.tls[0].hosts[0]
          value: jenkins.example.com
      - isNull:
          path: spec.tls[0].secretName
