suite: Controller Admin Additional Secrets
release:
  name: my-release
  namespace: my-namespace
templates:
  - secret-additional.yaml
tests:
  - it: tests defaults
    asserts:
      - hasDocuments:
          count: 0
  - it: tests 2 additional secrets
    set:
      controller.additionalSecrets:
        - name: something
          value: secret
        - name: anotherthing
          value: anothersecret
    asserts:
      - isKind:
          of: Secret
      - equal:
          path: apiVersion
          value: v1
      - equal:
          path: metadata.name
          value: my-release-jenkins-additional-secrets
      - equal:
          path: metadata.namespace
          value: my-namespace
      - matchRegex:
          path: metadata.labels["helm.sh/chart"]
          pattern: ^jenkins-
      - isNull:
          path: metadata.annotations
      - equal:
          path: data.something
          value: c2VjcmV0
      - equal:
          path: data.anotherthing
          value: YW5vdGhlcnNlY3JldA==
