apiVersion: v1
kind: Pod
spec:
  volumes:
  - name: ivy-cache
    emptyDir: {}
  - name: sbt-creds
    secret:
      secretName: sbt-publish-creds
      items:
      - key: credentials
        path: .credentials
  - name: docker-config
    configMap:
      name: docker-config
  containers:
  - name: sbt
    image: 185889327143.dkr.ecr.ap-southeast-1.amazonaws.com/sbt-0.13
    command: ['cat']
    tty: true
    volumeMounts:
    - name: ivy-cache
      mountPath: /root/.ivy2/cache
    - name: sbt-creds
      mountPath: /root/.ivy2/.credentials
      subPath: .credentials
  - name: kaniko
    image: gcr.io/kaniko-project/executor:v1.20.1
    command: ['cat']
    tty: true
    volumeMounts:
    - name: ivy-cache
      mountPath: /root/.ivy2/cache
    - name: docker-config
      mountPath: /kaniko/.docker
