{{- if .Values.controller.additionalSecrets -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "jenkins.fullname" . }}-additional-secrets
  namespace: {{ template "jenkins.namespace" . }}
  labels:
    {{ include "jenkins.labels" . | nindent 4 }}
type: Opaque
data:
{{- range .Values.controller.additionalSecrets }}
  {{ .name }}: {{ .value | b64enc }}
{{- end }}
{{- end }}
