{{- if and .Values.controller.httpsKeyStore.enable ( not  .Values.controller.httpsKeyStore.jenkinsHttpsJksSecretName ) (not .Values.controller.httpsKeyStore.disableSecretMount) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "jenkins.fullname" . }}-https-jks
  namespace: {{ template "jenkins.namespace" . }}
  labels:
    {{ include "jenkins.labels" . | nindent 4 }}
type: Opaque
data:
  jenkins-jks-file: |
{{ .Values.controller.httpsKeyStore.jenkinsKeyStoreBase64Encoded | indent 4 }}
  https-jks-password: {{ .Values.controller.httpsKeyStore.password | b64enc }}
{{- end }}
